name: Log in to GitHub Container Registry


# Triggert bei jedem Push auf main
on:
  push:
    branches:
      - main

# Erforderliche Workflow-Permissions
permissions:
  contents: read    # Checkout
  packages: write   # GHCR push

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1) Code auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Login beim GitHub Container Registry
      - name: Log in to GitHub Container Registry
  uses: docker/login-action@v2
  with:
    registry: ghcr.io
    username: ${{ github.actor }}
    password: ${{ secrets.GHCR_TOKEN }}

      # 3) Build & Push
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/stusab/djl-api:latest
