name: Build & Publish Docker Image
on:
  push:
    branches: [ main ]

# 1) Erlaube Write-Zugriff auf Packages
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 2) Repo auschecken
      - name: Checkout repository
        uses: actions/checkout@v4

      # 3) Login ins GHCR mit GITHUB_TOKEN
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4) Image bauen und pushen
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/djl-api:latest
